name: mobile_neurovision
description: NeuroVision â€” real-time neuro-tracking prototype (Flutter skeleton)
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+2
  provider: ^6.1.1
  permission_handler: ^11.3.0
  google_mlkit_face_detection: ^0.10.0
  image_picker: ^1.0.7
  http: ^1.1.2
  google_fonts: ^6.1.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.2.2
  path: ^1.8.3
  meta: ^1.10.0
  lottie: ^2.7.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
