name: mobile_neurovision
description: NeuroVision â€” real-time neuro-tracking prototype (Flutter skeleton)
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+4
  provider: ^6.0.5
  permission_handler: ^12.0.1
  image_picker: ^0.8.7+4
  http: ^0.13.6
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
